# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
before_all do		
ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
	end

after_all do |lane|
slack(message: "성공😎")
end	
error do |lane, exception|
slack(message: "실패😳", success:false)
end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

desc "My awesome app"
    lane :manna do
    gradle(task: "clean assembleRelease")
slack(message: "테스트다!")

        firebase_app_distribution(
            app: "1:847619466932:android:919a12f22246a2ab9e59e1",
firebase_cli_token: "1//0ecfFUOi6mQwXCgYIARAAGA4SNwF-L9IrIG1k4HFevQ5CbMX135kc7GGIgBlx1eiNHmFDyyjWnhmvtZ-eCGyaoEs23y6SUu-xXnM",
            testers: "yeonberry22@gmail.com, josh@watcha.com",
            release_notes: "테스트다! 존나 안되네 ㅅㅂ"
        )

    end
end
